global N;
N = 100;
T = 2;
t = 0:0.01:T;
dmax = 4;
umax = 20;
d = 2;
h = T/(N-1);
x0 = [(0:N-1)*d*h/T,(0:N-1)*pi*h/T, zeros(1,3*N)];
lb = [-dmax*ones(1,N) , -inf*ones(1,N) ,  -inf*ones(1,2*N) , -umax*ones(1,N)];
ub = [dmax*ones(1,N) , inf*ones(1,N) ,inf*ones(1,2*N) , umax*ones(1,N)];
options = optimoptions('fmincon','MaxFunctionEvaluations',3000);
x = fmincon(@myfun,x0,[],[],[],[],lb,ub,@mycon,options);
subplot(3,1,1);
plot(t,quadratic_spline(x(1:N),x(2*N+1:3*N),t));
subplot(3,1,3);
plot(t,quadratic_spline(x(N+1:2*N),x(3*N+1:4*N),t));
subplot(3,1,2);
plot(t,linear_spline(x(4*N+1:5*N),t));
%stem(x(4*N+1:5*N));